[package]
name = "blockchain_from_scratch"
version = "0.1.0"
edition = "2021"
authors = ["Faisal Al-Tameemi <faisal@mindsetlabs.io>"]
description = "A (basic) blockchain from scratch in Rust"

[dependencies]
sha2 = { version = "0.10.8" }
serde = { version = "1.0", features = ["derive"] }
